/* Operação fiscal autenticada. Nenhuma informação fiscal ou credencial é guardada no navegador. */
(() => {
  'use strict';
  const host=document.createElement('div'); host.id='patio-fiscal'; document.body.append(host);
  const root=host.attachShadow({mode:'open'});
  const $=s=>root.querySelector(s);
  root.innerHTML=`<button class="launcher" hidden>Notas fiscais</button><dialog><header><div><h1>Notas fiscais</h1><p>Homologação · emissão em produção bloqueada</p></div><button class="close" aria-label="Fechar notas fiscais">Fechar</button></header><nav><button data-view="list">Documentos</button><button data-view="new">Novo documento</button><button data-view="config">Emitente e parâmetros</button></nav><p class="notice" role="status" aria-live="polite"></p><main></main></dialog>`;
  let selected=null,busy=false,creationKey=null;
  async function request(path,method='GET',data) {
    const headers=typeof obterHeadersRequisicao==='function'?obterHeadersRequisicao({'Content-Type':'application/json'}):{'Content-Type':'application/json'};
    const r=await fetch('/api/fiscal'+path,{method,headers,credentials:'same-origin',...(data?{body:JSON.stringify(data)}:{})});
    const body=await r.json().catch(()=>({})); if(!r.ok)throw Error(body.error||'Não foi possível concluir a operação fiscal.'); return body;
  }
  function message(text=''){ $('.notice').textContent=text; }
  async function action(fn){if(busy)return;busy=true;root.querySelectorAll('button').forEach(x=>x.disabled=true);message('Processando…');try{await fn();}catch(e){message(e.message);}finally{busy=false;root.querySelectorAll('button').forEach(x=>x.disabled=false);}}
  function el(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
  function field(parent,name,label,value='',type='text') {const wrapper=el('label',label),input=el(type==='textarea'?'textarea':'input');input.name=name; if(type!=='textarea')input.type=type;input.value=value??'';wrapper.append(input);parent.append(wrapper);return input;}
  function button(parent,label,handler){const b=el('button',label);b.type='button';b.onclick=()=>action(handler);parent.append(b);return b;}
  const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  async function list(){selected=null;const data=await request('/documentos');const main=$('main');main.replaceChildren();main.append(el('h2','Documentos da oficina'));
    const source=el('div'); const os=field(source,'os','Número interno da OS');button(source,'Preparar a partir da OS',async()=>{await request('/os/'+encodeURIComponent(os.value),'POST',{});await list();message('Rascunhos preparados. Revise destinatário e classificação fiscal.');});main.append(source);
    if(!data.documentos.length)main.append(el('p','Nenhum documento fiscal cadastrado.'));
    const table=el('table');const header=el('tr');for(const text of ['Documento','Situação','Total','Ação'])header.append(el('th',text));table.append(header);
    for(const d of data.documentos){const tr=el('tr');tr.append(el('td',`${d.modelo} · série ${d.serie} · ${d.numero||'rascunho'}`),el('td',d.status),el('td',money(d.totais.valorTotalDocumento)));const td=el('td');button(td,'Abrir',()=>detail(d.id));tr.append(td);table.append(tr);}main.append(table);message(`${data.total} documento(s). Exibindo até 50.`);
  }
  async function detail(id){const doc=await request('/documentos/'+encodeURIComponent(id));selected=doc;const main=$('main');main.replaceChildren();main.append(el('h2',`${doc.modelo} — ${doc.status}`),el('p',`Série ${doc.serie} · número ${doc.numero||'não reservado'} · ${money(doc.totais.valorTotalDocumento)}`),el('p',`Destinatário: ${doc.destinatario.nome||'pendente'}`));
    if(doc.motivoStatusSefaz||doc.mensagemErro)main.append(el('p',doc.motivoStatusSefaz||doc.mensagemErro));
    for(const it of doc.itens)main.append(el('p',`${it.quantidade} × ${it.descricao} — ${money(it.valorBruto)}`));
    main.append(el('p',doc.evidencia));
    if(doc.protocoloAutorizacao)main.append(el('p','Protocolo: '+doc.protocoloAutorizacao));
    const controls=el('div');main.append(controls);
    if(['rascunho','rejeitado'].includes(doc.status))button(controls,'Corrigir dados',()=>editor(doc));
    if(doc.status==='rascunho'){button(controls,'Validar revisão fiscal',async()=>{await request('/documentos/'+id+'/revisar','POST',{});await detail(id);message('Revisão registrada. Confira a composição antes da transmissão.');});if(doc.reviewedAt)button(controls,'Transmitir em homologação',async()=>{if(!confirm('Transmitir este documento ao ambiente de homologação do provedor?'))return;await request('/documentos/'+id+'/transmitir','POST',{});await detail(id);});}
    if(!['rascunho','cancelado'].includes(doc.status))button(controls,'Consultar situação',async()=>{await request('/documentos/'+id+'/consultar','POST',{});await detail(id);});
    button(controls,'Exportar para contabilidade',async()=>{const data=await request('/documentos/'+id+'/exportar');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='exportacao-fiscal-'+id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('Exportação preparada com documentos e eventos disponíveis.');});
    if(doc.danfeUrl)button(controls,'Baixar representação auxiliar',async()=>{const headers=typeof obterHeadersRequisicao==='function'?obterHeadersRequisicao():{};const r=await fetch('/api/fiscal/documentos/'+id+'/pdf',{headers,credentials:'same-origin'});if(!r.ok){const error=await r.json();throw Error(error.error||'PDF indisponível.');}const url=URL.createObjectURL(await r.blob()),a=el('a');a.href=url;a.download='representacao-'+id+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
    if(doc.xmlOficial)button(controls,'Baixar XML oficial',async()=>{const headers=typeof obterHeadersRequisicao==='function'?obterHeadersRequisicao():{};const r=await fetch('/api/fiscal/documentos/'+id+'/xml',{headers,credentials:'same-origin'});if(!r.ok)throw Error('Download recusado ou integridade não confirmada.');const url=URL.createObjectURL(await r.blob()),a=el('a');a.href=url;a.download=`fiscal-${id}.xml`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('XML recuperado.');});
    if(doc.status==='autorizado'){main.append(el('p','Cancelamento não estorna estoque ou recebimentos. CC-e não pode alterar valores, tributos, identidade do emitente/destinatário ou data de emissão.'));
      const text=field(main,'evento','Justificativa do cancelamento ou texto completo da correção','','textarea');
      button(main,'Solicitar cancelamento',async()=>{if(!confirm('Solicitar cancelamento fiscal em homologação?'))return;await request('/documentos/'+id+'/cancelar','POST',{justificativa:text.value});await detail(id);});
      if(doc.modelo==='55')button(main,'Enviar carta de correção',async()=>{if(!confirm('Confirma que o texto respeita as restrições da CC-e e foi revisado?'))return;await request('/documentos/'+id+'/cce','POST',{correcao:text.value});await detail(id);});}
    const events=await request('/documentos/'+id+'/eventos');for(const e of events)main.append(el('p',`${e.tipoEvento} #${e.sequencial}: ${e.status} · ${e.protocolo||'protocolo pendente'}`));
    if(doc.providerPayload){const details=el('details');details.append(el('summary','Composição revisada enviada ao provedor'),el('pre',JSON.stringify(doc.providerPayload,null,2)));main.append(details);}
    main.append(el('small','NFC-e, inutilização, substituição, devolução e contingência não disponíveis nesta versão.'));message(doc.reviewedAt?'Revisão fiscal registrada.':'');
  }
  function editor(doc=null){creationKey=doc?null:crypto.randomUUID();selected=doc;const main=$('main');main.replaceChildren();main.append(el('h2',doc?'Corrigir documento':'Preparar documento'),el('p','Preencha os códigos e alíquotas validados pelo contador. Campos vazios impedem a revisão; não use zero para representar informação desconhecida.'));
    const form=el('form'),model=el('select');model.name='modelo';for(const [v,label] of [['55','NF-e · peças'],['NFS-e','NFS-e · serviços municipais']]){const o=el('option',label);o.value=v;model.append(o);}model.value=doc?.modelo||'55';model.disabled=!!doc;const ml=el('label','Documento');ml.append(model);form.append(ml);
    const dest=el('fieldset');dest.append(el('legend','Destinatário / tomador'));const d=doc?.destinatario||{};
    for(const [name,label] of Object.entries({nome:'Nome / razão social',documento:'CPF / CNPJ',logradouro:'Logradouro',numero:'Número',bairro:'Bairro',municipio:'Município',codigoMunicipio:'Código IBGE',uf:'UF',cep:'CEP',indicadorIE:'Indicador de IE',inscricaoEstadual:'Inscrição estadual'}))field(dest,name,label,d[name]);form.append(dest);
    const items=el('section');form.append(items);
    function addItem(input={}){const row=el('fieldset');row.append(el('legend','Item'));for(const [name,label] of Object.entries({descricao:'Descrição',codigoInterno:'Código interno',quantidade:'Quantidade',valorUnitario:'Valor unitário',desconto:'Desconto',unidade:'Unidade',ncm:'NCM',cfop:'CFOP',origem:'Origem',csosn:'CSOSN (Simples)',cstICMS:'CST ICMS (normal)',cstPIS:'CST PIS',cstCOFINS:'CST COFINS',aliquotaICMS:'Alíquota ICMS (%)',aliquotaPIS:'Alíquota PIS (%)',aliquotaCOFINS:'Alíquota COFINS (%)',aliquotaCBS:'Alíquota CBS (%)',aliquotaIBS:'Alíquota IBS (%)',itemListaServico:'Item da lista de serviço',codigoTributacaoMunicipio:'Código municipal de tributação',aliquotaISS:'Alíquota ISS (%)'}))field(row,name,label,input[name]);const retention=el('select');retention.name='issRetido';for(const [value,label] of [['','Retenção de ISS: informar'],['false','ISS não retido'],['true','ISS retido']]){const opt=el('option',label);opt.value=value;retention.append(opt);}retention.value=input.issRetido===undefined?'':String(input.issRetido);row.append(retention);
      const advanced=el('details');advanced.append(el('summary','Campos adicionais revisados do provedor (JSON)'));field(advanced,'camposProvedor','Campos específicos',JSON.stringify(input.camposProvedor||{},null,2),'textarea');row.append(advanced);button(row,'Remover item',async()=>row.remove());items.append(row);}
    for(const it of doc?.itens||[{}])addItem(it.fiscalInput||it);button(form,'Adicionar item',async()=>addItem());
    button(form,'Salvar rascunho',async()=>{const destinatario=Object.fromEntries([...dest.querySelectorAll('input')].map(x=>[x.name,x.value]));const list=[...items.children].map(row=>{const v={};for(const x of row.querySelectorAll('input,select')){if(x.value!=='')v[x.name]=x.name==='issRetido'?x.value==='true':x.value;}v.camposProvedor=JSON.parse(row.querySelector('textarea').value||'{}');return v;});const body={modelo:model.value,destinatario,itens:list,idempotencyKey:creationKey};const saved=await request('/documentos'+(doc?'/'+doc.id:''),doc?'PUT':'POST',body);await detail(saved.id);});form.onsubmit=e=>e.preventDefault();main.append(form);message('');
  }
  async function config(){const c=await request('/config'),main=$('main');main.replaceChildren();main.append(el('h2','Emitente e cobertura fiscal'),el('p',`Provedor Focus · token no servidor: ${c.hasProviderToken?'configurado':'pendente'}. Certificado e assinatura são custodiados pelo provedor. Nunca cole segredos neste formulário.`));const form=el('form');
    for(const [name,label] of Object.entries({cnpj:'CNPJ',razaoSocial:'Razão social',nomeFantasia:'Nome fantasia',inscricaoEstadual:'Inscrição estadual',inscricaoMunicipal:'Inscrição municipal',uf:'UF',codigoMunicipioIbge:'Código IBGE do município',regimeTributario:'Regime (simples_nacional, lucro_presumido ou lucro_real)',cnaePrincipal:'CNAE principal',nfeSerie:'Série NF-e',nfeProximoNumero:'Primeiro número NF-e, conforme histórico',nfseSerie:'Série RPS',nfseProximoNumero:'Primeiro número RPS, conforme histórico'}))field(form,name,label,c[name]);
    const profiles=field(form,'regrasTributarias','Perfis fiscais versionados e validados pelo contador (JSON)',JSON.stringify(c.regrasTributarias,null,2),'textarea');profiles.rows=14;
    button(form,'Salvar configuração de homologação',async()=>{const body=Object.fromEntries([...form.querySelectorAll('input')].map(x=>[x.name,x.value]));body.ambiente='homologacao';body.provider='focus_nfe';body.regrasTributarias=JSON.parse(profiles.value);await request('/config','PUT',body);message('Configuração salva. A numeração já reservada nunca retrocede.');});form.onsubmit=e=>e.preventDefault();main.append(form);message('');
  }
  document.addEventListener('click',event=>{if(event.target.closest('[data-act="fiscal-open"]')){$('dialog').showModal();action(list);}});
  $('.launcher').onclick=()=>{$('dialog').showModal();action(list);};$('.close').onclick=()=>$('dialog').close();root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>action(()=>b.dataset.view==='list'?list():b.dataset.view==='config'?config():editor()));
  const style=el('style');style.textContent=`:host{font:14px system-ui;color:#142d40}.launcher{position:fixed;right:20px;top:16px;z-index:9000;background:#173e52;color:white}button{padding:10px 14px;border:1px solid #b6c9d2;border-radius:8px;cursor:pointer;margin:4px;background:#fff;color:#173e52}button:disabled{opacity:.5;cursor:wait}dialog{width:min(1060px,94vw);height:88vh;max-width:94vw;padding:0;border:0;border-radius:14px;background:#f5f8fa;color:#142d40}dialog::backdrop{background:#12273499}header{display:flex;justify-content:space-between;padding:18px 24px;background:#173e52;color:white}h1,h2{margin:0 0 8px}header p{margin:0}nav,main,.notice{padding:12px 24px}.notice{margin:0;color:#713b00;background:#fff3da;white-space:pre-wrap}.notice:empty{display:none}main{padding-bottom:36px}label{display:flex;flex-direction:column;gap:5px;margin:8px 4px;min-width:190px;flex:1}input,select,textarea{font:inherit;padding:10px;border:1px solid #b6c9d2;border-radius:6px;max-width:100%;box-sizing:border-box;background:white}fieldset{display:flex;flex-wrap:wrap;gap:8px;border:1px solid #d1dde3;margin:16px 0;border-radius:8px}legend{font-weight:700}details{width:100%;margin:12px 0}textarea{width:100%;min-height:110px}table{border-collapse:collapse;width:100%;margin-top:16px}td,th{text-align:left;padding:12px;border-bottom:1px solid #d1dde3}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}small{display:block;margin-top:20px}@media(max-width:640px){header,main,nav,.notice{padding:12px}.launcher{top:8px;right:8px}label{min-width:130px}td,th{padding:6px}}`;root.prepend(style);
  request('/config').then(()=>{window.patioFiscalAvailable=true;if(typeof renderNav==='function' && typeof S!=='undefined' && S)renderNav();}).catch(()=>host.remove());
})();
