'use strict';

// Editorial assessment grounded in repository sources; no provider calls or customer data.
const sources = [
  { title: 'Anúncio do Jev · 15/09/2026', url: 'https://typesafe.ai/blog/introducing-system-one-models-and-jev', note: 'Lançamento e benchmarks do próprio fornecedor; não são medições deste CRM.' },
  { title: 'Modelos, preço e modalidades', url: 'https://docs.typesafe.ai/models', note: 'Consulta em 28/09/2026: jev-1.13.0, texto, US$ 0,042 por milhão de tokens de entrada; saída sem cobrança. Preço sujeito a revisão.' },
  { title: 'Contrato HTTP da API', url: 'https://docs.typesafe.ai/api', note: 'POST /v1/systemone; state + questions; Choice, Score e Noul. Choice admite até 255 opções.' },
  { title: 'Probabilidade e confiança', url: 'https://docs.typesafe.ai/confidence', note: 'Confidence é derivada da distribuição; não equivale à taxa de acerto observada no português da oficina. Noul não tem confidence separado.' },
  { title: 'Limitações declaradas do Jev 1.13', url: 'https://docs.typesafe.ai/model-jaggedness/jev-1.13', note: 'Pode errar em números, datas, instruções adversariais e contexto irrelevante. Saída válida não garante decisão correta.' },
  { title: 'Políticas de dados do fornecedor', url: 'https://docs.typesafe.ai/legal', note: 'Validar contrato, retenção e destino dos dados antes de mudar o provedor de suporte. Não presumir que o consentimento atual ao Gemini abrange a TypeSafe.' },
];

const cases = [
  {
    id: 'suporte', number: '01', title: 'Escolher o artigo certo no suporte', category: 'Suporte', status: 'AGORA', stage: 'Experimento isolado', score: 8, impact: 8, complexity: 3, hours: [16, 32], tokens: 1800,
    summary: 'O encaixe mais direto: substituir somente a classificação externa de um catálogo fechado.',
    current: 'SupportAgent.answer tenta regras e busca local; sem artigo inequívoco, com consentimento e modelo configurado, o Gemini retorna articleId. Artigos e mensagens locais de esclarecimento/encaminhamento são predefinidos; a saída livre do Gemini não é exibida.',
    flow: 'Mensagem sanitizada → políticas obrigatórias → busca local → Jev Choice(articleId | desconhecido) → limiar validado → artigo existente ou pessoa.',
    decision: 'AGORA vale preparar corpus e comparador isolado. Não habilitar Jev no atendimento real sem evidência e acesso ao provedor. O piloto não comprova volume nem gasto de IA.',
    benefit: 'Hipótese: menos encaminhamentos por sinônimos e menor custo/latência no ramo que já chama IA. Não atribuir ao Jev atendimentos que a busca local já resolve.',
    pros: ['Reaproveita base revisada e contrato de resposta.', 'Troca pequena e reversível em uma fronteira de classificação existente.'],
    cons: ['Integração, avaliação e manutenção custam mais que tokens no piloto.', 'Português, jargão e catálogo precisam de avaliação própria; o baseline já valida um enum.'],
    risks: 'Artigo errado, confiança excessiva e envio de dados ao novo fornecedor. A sanitização atual reduz dados, mas não anonimiza todo texto livre.',
    trigger: 'Para promover: amostra inicial de 200 perguntas PT-BR revisadas, ganho mensurável sobre busca local/Gemini e payback ≤ 6 meses. 500 dúvidas ambíguas/mês é um ponto de revisão proposto, não demanda observada.',
    files: ['services/support/agent.js', 'services/support/index.js', 'services/support/router.js', 'services/support/privacy.js', 'services/support/knowledge.js', 'js/support-widget.js', 'docs/SUPORTE_IA.md'],
    evidence: [{ file: 'services/support/agent.js', needle: 'if (!article && aiConsent && this.aiAvailable)' }, { file: 'services/support/router.js', needle: 'req.body.aiConsent' }, { file: 'services/support/knowledge.js', needle: 'function search(query)' }],
    action: 'Criar services/ai/jevClassifier.js com cliente injetável e scripts/evaluate-jev-support.cjs. Comparar offline busca local, classificador atual e Jev sobre o mesmo conjunto. Integrar opcionalmente no ramo externo de SupportAgent, com feature flag desligada. Preservar o formato text/references/handoff/priority/mode; ajustar opt-in para nomear o provedor escolhido e registrar a versão do consentimento. Não ativar o novo provedor com um consentimento legado que só nomeia Gemini.',
    acceptance: 'Separar desenvolvimento e holdout por pergunta/paráfrase; incluir fora de escopo, incidentes, pedido humano e prompt injection. No holdout, precisão ≥ 95% entre respostas aceitas, cobertura não inferior ao baseline e zero falhas nas regras obrigatórias. Relatar tamanho por classe e intervalo de incerteza; 200 exemplos não certificam segurança. Só promover se custo total ou p95 melhorar sem regressão. Sem consentimento: zero chamadas externas.',
    metrics: 'mode, versão do catálogo/modelo, latência p50/p95, tokens, custo, taxa de abstenção, artigos corrigidos, handoff e motivo; identificadores pseudônimos e sem texto bruto.',
    fallback: 'Erro, timeout, 429, opção inválida, baixa confiança ou circuito aberto → orientação local, esclarecimento ou humano. Não chamar Gemini automaticamente se o consentimento não o permitir. Flag off restaura o comportamento atual.',
    tests: ['tests/support_agent.test.cjs'],
  },
  {
    id: 'incidentes', number: '02', title: 'Priorizar relatos de incidente', category: 'Segurança / suporte', status: 'DEPOIS', stage: 'Fila humana', score: 6, impact: 6, complexity: 4, hours: [24, 40], tokens: 1600,
    summary: 'Complementar as palavras-chave do suporte quando relatos importantes escaparem da triagem.',
    current: 'O agente reconhece vazamento, invasão, fraude e pedido de pessoa por expressões regulares; encaminha com prioridade. Existe inbox humana e fluxo de resposta a incidentes.',
    flow: 'Relato já autorizado → regras de emergência → Jev Noul(relata possível incidente?) → apenas elevar prioridade da fila humana.',
    decision: 'DEPOIS, como extensão da mesma fronteira do suporte. Não criar um segundo chatbot nem um serviço de bloqueio automático.',
    benefit: 'Hipótese: captar relatos indiretos, como “apareceu a oficina de outra empresa”, e reduzir tempo de triagem.',
    pros: ['Decisão estreita sobre texto existente.', 'Pode ser agrupada com a classificação do suporte, quando ambas forem elegíveis.'],
    cons: ['Incidentes raros produzem muitos falsos alarmes.', 'Depende de equipe responsável; priorização sem resposta humana não resolve o incidente.'],
    risks: 'Falso negativo não pode neutralizar regra existente. Noul é um sinal do relato, não prova de invasão. Não enviar credenciais para análise.',
    trigger: 'Reavaliar após 2 relatos críticos perdidos pela regra em 30 dias ou > 100 tickets/dia com atraso de triagem; ambos são gatilhos propostos.',
    files: ['services/support/agent.js', 'services/support/repository.js', 'services/support/router.js', 'public/support/inbox.js', 'services/incidentResponseService.js'],
    evidence: [{ file: 'services/support/agent.js', needle: 'const urgent =' }, { file: 'services/support/agent.js', needle: "priority: urgent ? 'urgent'" }],
    action: 'Acrescentar classificador complementar de possível incidente ao suporte, condicionado a opt-in para o provedor. Acrescentar prioridade sugerida e razão enumerada na fila. Regras críticas sempre prevalecem; jamais bloquear conta, resetar senha ou encerrar ocorrência por resultado de IA.',
    acceptance: 'Conjunto PT-BR revisado com relatos indiretos, negações e injeção; zero rebaixamento de incidentes detectados pelas regras. Medir recall e falsos positivos em holdout e exigir aprovação do responsável do suporte sobre a carga adicional. Sem regra positiva e sem IA válida, preservar fila normal com pedido humano disponível.',
    metrics: 'Incidentes confirmados/rejeitados pelo atendente, tempo até assunção, recall auditado, falsos positivos por 100 tickets e custo incremental; não logar relato bruto.',
    fallback: 'Preservar regex, botão de atendimento humano e protocolo atual. Nunca descartar relato quando o classificador falhar.',
    tests: ['tests/support_agent.test.cjs', 'tests/workshop_day.test.cjs'],
  },
  {
    id: 'intencoes', number: '03', title: 'Rotear comandos de texto', category: 'Voz / chatbot', status: 'DEPOIS', stage: 'Somente intenção', score: 6, impact: 7, complexity: 7, hours: [40, 72], tokens: 1800,
    summary: 'Separar intenção e extração, começando por comandos de consulta já digitados.',
    current: 'interpretarComando envia texto ou áudio ao Gemini para interpretar intenção e campos; interpretarPorRegras é o fallback. executarAcao aplica controles e confirmações.',
    flow: 'Texto disponível → comandos exatos locais → Jev Choice(intenção | ambígua) → handler existente; campos extraídos e validados separadamente.',
    decision: 'DEPOIS. A troca integral do Gemini não cabe: Jev não transcreve áudio nem gera os campos livres ou a resposta falada.',
    benefit: 'Hipótese: dispensar uma chamada generativa em consultas textuais cuja entidade já esteja resolvida no contexto autorizado.',
    pros: ['Intenções enumeradas já existem.', 'Pode reduzir chamadas em uma fração simples dos comandos.'],
    cons: ['Adicionar Jev antes de toda chamada Gemini aumenta custo e latência.', 'Separar interpretação de extração exige refatoração e testes de execução.'],
    risks: 'Confundir consulta com mutação; executar no tenant errado; contornar confirmação. Confiança alta nunca autoriza uma ação.',
    trigger: 'Canal ativo, ≥ 5.000 comandos textuais/mês e ≥ 30% resolvíveis sem extração livre; ou latência de consultas comprovadamente prejudicial. Medir economia da cascata completa.',
    files: ['services/voiceActionEngine.js', 'services/technicalIntakeEngine.js', 'lib/tokens/securityToken.js', 'server.js', 'js/voz.js'],
    evidence: [{ file: 'services/voiceActionEngine.js', needle: 'async function interpretarComando' }, { file: 'services/voiceActionEngine.js', needle: 'async function executarAcao' }, { file: 'server.js', needle: "app.post('/api/comando-voz'" }],
    action: 'Criar roteamento opcional só para input.text, com consultas permitidas explicitamente e contexto obtido no servidor. Manter áudio na pipeline existente. Iniciar em shadow mode que registra previsão sem executar; depois liberar apenas consultas com entidades determinadas. Mutação continua na execução atual, com RBAC, tokens e controle de versão.',
    acceptance: 'Testar negação, duas intenções, “não excluir”, confirmação por outro usuário, token expirado e outro tenant. Nenhuma mutação pelo novo atalho; ambiguidade retorna ao fluxo existente. Comparar p95 e custo total incluindo fallback, não apenas a chamada Jev.',
    metrics: 'Intenção prevista/corrigida, taxa de atalhos seguros, discordância, custo por comando completo, p95 fim a fim, abstenção e violações bloqueadas.',
    fallback: 'interpretarComando atual com Gemini quando permitido, interpretarPorRegras ou entrada manual. Preservar confirmação explícita; nunca transformar baixa confiança em execução.',
    tests: ['tests/voice.test.cjs', 'tests/voice_security_negative.test.cjs', 'tests/http_voice_confirmation_recovery.test.cjs'],
  },
  {
    id: 'triagem', number: '04', title: 'Classificar a queixa técnica', category: 'Triagem / classificação', status: 'DEPOIS', stage: 'Sugestão ao operador', score: 5, impact: 6, complexity: 5, hours: [32, 56], tokens: 1400,
    summary: 'Melhorar a categoria de queixas que escapam aos termos do catálogo, sem diagnosticar o veículo.',
    current: 'identificarDominioTecnico e classificarTexto percorrem termos conhecidos. A categoria orienta perguntas e detecção de recorrência na Pré-OS.',
    flow: 'Queixa em texto → regra local → Jev Choice(categorias atuais | geral | múltiplas) nos casos ambíguos → operador confirma → triagem existente.',
    decision: 'DEPOIS de medir erros; primeiro ampliar sinônimos revisados. Não alterar automaticamente garantia, serviço, preço ou liberação do veículo.',
    benefit: 'Hipótese: menos queixas genéricas e perguntas mais relevantes para descrições coloquiais do motorista.',
    pros: ['Taxonomias pequenas e explícitas.', 'Possibilidade de abstenção e confirmação humana.'],
    cons: ['As duas taxonomias existentes não são idênticas; exigem mapeamento.', 'Sinônimos locais podem resolver por custo menor.'],
    risks: 'Classificação incorreta pode mascarar sintoma ou influenciar a recorrência. Não usar como diagnóstico mecânico nem como decisão de garantia.',
    trigger: '≥ 1.000 triagens/mês e > 15% em GERAL/OUTROS ou corrigidas, após manutenção do dicionário. Começar com 300 queixas rotuladas por especialista.',
    files: ['services/intakeQuestionEngine.js', 'services/recurrenceDetector.js', 'services/preOSEngine.js', 'services/technicalIntakeEngine.js', 'services/warrantyService.js'],
    evidence: [{ file: 'services/intakeQuestionEngine.js', needle: 'function identificarDominioTecnico' }, { file: 'services/recurrenceDetector.js', needle: 'function classificarTexto' }, { file: 'services/preOSEngine.js', needle: 'const recorrencia = detectarRecorrencia' }],
    action: 'Introduzir sugestão opcional de categoria antes da abertura da Pré-OS; preservar função síncrona de regras e separar avaliação externa da transação. Definir mapeamento explícito entre DOMINIOS_TRIAGEM e CATALOGO_CATEGORIAS. Guardar categoria original, sugerida e confirmada sem substituir o texto da queixa.',
    acceptance: 'Corpus revisado por mecânico, incluindo múltiplos sintomas, negação e termos regionais; ganho em macro-F1 sobre dicionário ampliado no holdout. Garantia, datas, km e decisão de reparo permanecem determinísticos/humanos. Nenhuma chamada externa com transação SQLite aberta.',
    metrics: 'Correções por categoria, GERAL/OUTROS, macro-F1, abstenção, tempo de triagem e falsos vínculos de recorrência revisados.',
    fallback: 'Catálogo de termos e pergunta geral atuais; escolha manual do domínio. Se não houver ganho sobre sinônimos, remover experimento.',
    tests: ['tests/technical_intake.test.cjs', 'tests/pre_os.test.cjs', 'tests/progressive_os.test.cjs'],
  },
  {
    id: 'documentos', number: '05', title: 'Rotear documentos após OCR', category: 'Documentos / WhatsApp', status: 'DEPOIS', stage: 'Canal hoje bloqueado', score: 4, impact: 4, complexity: 6, hours: [40, 64], tokens: 2200,
    summary: 'Escolher o tipo de documento usando texto já extraído, quando houver uma fila documental real.',
    current: 'analisarDocumentoWhatsApp combina classificação e extração multimodal no Gemini; usa Tesseract e heurísticas como fallback. O handler bloqueia compras, notas e comprovantes no piloto.',
    flow: 'OCR/texto existente → Jev Choice(pedido, nota, comprovante, placa, outro) → fila apropriada → revisão/extração atual.',
    decision: 'DEPOIS, somente após homologar o canal. Não acrescentar OCR caro só para alimentar Jev nem reabrir as mutações bloqueadas.',
    benefit: 'Hipótese: menos documentos enviados ao fluxo errado; ganho depende de reutilizar OCR e evitar uma chamada que seria necessária.',
    pros: ['Tipos já definidos no código.', 'Saída curta e abstenção para documentos ilegíveis.'],
    cons: ['Não recebe imagem; OCR permanece necessário.', 'Classificação não elimina extração de itens, valores e nomes.'],
    risks: 'Erro de OCR, dados financeiros enviados ao provedor e confusão entre recibo e comprovação bancária. Tipo “comprovante” não atesta autenticidade nem liquidação.',
    trigger: 'Canal aprovado, ≥ 2.000 documentos/mês e custo/erro medido no roteamento; demonstrar economia da cadeia OCR + classificação + extração + revisão.',
    files: ['server.js', 'js/whatsapp.js', 'services/procurementService.js', 'services/inventoryService.js'],
    evidence: [{ file: 'server.js', needle: 'async function analisarDocumentoWhatsApp' }, { file: 'server.js', needle: "docAnalise.tipo === 'comprovante_pagamento'" }],
    action: 'Extrair o classificador documental para serviço próprio e incluir Jev apenas após texto OCR existente. Tratar o resultado como sugestão de fila. Preservar todos os returns que bloqueiam mutações do WhatsApp no piloto. Não chamar processarComprovantePagamento a partir da classificação.',
    acceptance: 'Testar nota, pedido, recibo falso, ilegível, texto injetado e imagem sem OCR. Contratos monetários e validação de NF não mudam. Testar por HTTP/handler que classificar comprovante não gera movimento nem baixa. Benchmark completo deve incluir OCR.',
    metrics: 'Confusão entre tipos, taxa de revisão, OCR sem texto, latência total, custo total por documento e qualquer tentativa bloqueada de mutação.',
    fallback: 'Heurística textual ou seleção humana; manter a mensagem de canal bloqueado. Gemini somente no fluxo multimodal autorizado atual.',
    tests: ['tests/voice.test.cjs', 'tests/http.test.cjs', 'tests/monetary_contracts.test.cjs'],
  },
  {
    id: 'auth', number: '06', title: 'Autenticação e permissões', category: 'Autenticação', status: 'NÃO USAR', stage: 'Manter determinístico', score: 0, impact: 0, complexity: 8, hours: [40, 80], tokens: 0,
    summary: 'Senha, token, papel e tenant têm respostas exatas. Um modelo acrescentaria risco e dependência.',
    current: 'scrypt, comparação segura, memberships, lockout, securityContext e RBAC em lib/auth; tokens de ação separados.',
    flow: 'Não inserir Jev no login, na validação de sessão, na escolha do tenant ou no requirePermission.',
    decision: 'NÃO USAR, independentemente de escala, para conceder acesso.',
    benefit: 'Nenhum benefício claro sobre verificações criptográficas e regras. Preservá-las evita disponibilidade dependente de IA.',
    pros: ['Não há vantagem técnica demonstrada para o Jev neste ponto.'],
    cons: ['Falso aceite é falha de segurança.', 'Rede e custo adicionados a toda autenticação.'],
    risks: 'Escalada de privilégio, acesso entre tenants e indisponibilidade no login.',
    trigger: 'Nenhum volume justifica autenticação probabilística. Incidentes podem justificar telemetria e triagem humana separada (caso 02).',
    files: ['lib/auth/identity.js', 'lib/auth/context.js', 'lib/auth/userRepository.js', 'lib/tokens/securityToken.js'],
    evidence: [{ file: 'lib/auth/userRepository.js', needle: 'crypto.scryptSync' }, { file: 'lib/auth/context.js', needle: 'function createAuthMiddleware' }],
    action: 'Não integrar Jev. Revisar as fronteiras de autorização e documentar que modelos não produzem securityContext, roles ou permissões. Acrescentar regressões apenas se descobrir lacuna reproduzível.',
    acceptance: 'Login e RBAC funcionam com todas as IAs desabilitadas; tenant e papel sempre derivados de credenciais verificadas. Nenhuma previsão substitui validação criptográfica.',
    metrics: 'Falhas de autenticação por tipo, bloqueios e latência usando lib/metrics.js, sem senhas ou tokens.',
    fallback: 'Credencial inválida ou permissão ausente → negar deterministicamente. Fluxo de recuperação existente.',
    tests: ['tests/persistent_auth_and_rbac.test.cjs', 'tests/multi_tenant_security.test.cjs', 'tests/auth_lockout_audit_and_rbac_preservation.test.cjs'],
  },
  {
    id: 'fraude', number: '07', title: 'Antifraude e comprovantes', category: 'Fraude / cobrança', status: 'NÃO USAR', stage: 'Sem evidência de ROI', score: 2, impact: 2, complexity: 9, hours: [80, 160], tokens: 0,
    summary: 'Um classificador de texto não comprova pagamento nem substitui o provedor financeiro.',
    current: 'Billing verifica webhooks e deduplica eventos no SQLite. Comprovantes via WhatsApp não fazem baixa no handler do piloto.',
    flow: 'Provedor → verificação de webhook → idempotência → atualização determinística. Não incluir score Jev como autorização de liquidação.',
    decision: 'NÃO USAR agora como motor antifraude ou certificador de comprovantes. Não há conjunto de perdas/chargebacks rotulado no levantamento.',
    benefit: 'Ganho não demonstrado; score sem dados de resultado pode criar falsa sensação de proteção.',
    pros: ['Em cenário futuro, texto de contestação poderia ser triado para uma pessoa; não é prova de fraude.'],
    cons: ['Sem acesso à verdade bancária.', 'Falso positivo prejudica cliente; falso negativo pode liberar baixa indevida.'],
    risks: 'Confiar em imagem/texto adulterado, cobrança indevida e decisão não auditável. Saída válida não equivale a transação válida.',
    trigger: 'Reabrir apenas para triagem auxiliar se houver perdas materiais e corpus rotulado, por exemplo ≥ 10.000 eventos/mês com análise de custo do erro; priorizar sinais do provedor.',
    files: ['services/billing/billingService.js', 'services/billing/paymentProviderAdapter.js', 'server.js'],
    evidence: [{ file: 'services/billing/billingService.js', needle: 'async function processWebhookEvent' }, { file: 'server.js', needle: "docAnalise.tipo === 'comprovante_pagamento'" }],
    action: 'Não integrar Jev. Mapear e verificar contratos de autenticação dos webhooks por adapter, idempotência durável, reconciliação com provedor e bloqueio atual de baixa pelo WhatsApp. Corrigir apenas falhas reproduzidas em ambiente isolado.',
    acceptance: 'Webhook inválido não altera assinatura; replay não duplica efeito; foto ou texto de recibo não confirma liquidação. Cobrir o adapter real configurado sem depender de chamadas reais em testes.',
    metrics: 'Webhook rejeitado, replay, divergência de reconciliação e perda confirmada, com identificadores minimizados.',
    fallback: 'Evento não verificado fica pendente de reconciliação/humano; nunca transformar falha de IA em aprovação.',
    tests: ['tests/durable_billing.test.cjs', 'tests/saas_customer_lifecycle.test.cjs', 'tests/http.test.cjs'],
  },
  {
    id: 'transacoes', number: '08', title: 'Transações, caixa e estoque', category: 'Transações', status: 'NÃO USAR', stage: 'Cálculo e invariantes', score: 0, impact: 0, complexity: 7, hours: [48, 96], tokens: 0,
    summary: 'Concorrência, saldo e valor monetário precisam de garantias exatas, não de julgamento semântico.',
    current: 'SQLite WAL, BEGIN IMMEDIATE, filas por tenant, versões e serviços financeiros/estoque. Existem testes monetários e de isolamento.',
    flow: 'RBAC → validação de domínio → transação/versionamento → auditoria. Jev fora do caminho de commit.',
    decision: 'NÃO USAR para decidir commit, calcular saldo, custo, preço mínimo, estoque ou aprovação de orçamento.',
    benefit: 'Nenhuma vantagem clara. Regras locais são mais rápidas, baratas e reproduzíveis.',
    pros: ['Jev não agrega garantia transacional.'],
    cons: ['Não elimina locks, validação ou idempotência.', 'Chamadas externas dentro de transação aumentariam contenção.'],
    risks: 'Perda de atualização, saldo incorreto, estoque negativo e arredondamento indevido.',
    trigger: 'Nenhum volume justifica IA para invariantes exatos. Crescimento justifica otimização do banco e testes de concorrência.',
    files: ['db.js', 'lib/repository/stateRepository.js', 'services/financialEngine.js', 'services/inventoryService.js', 'services/pricingEngine.js', 'services/quotationService.js'],
    evidence: [{ file: 'db.js', needle: "await txObj.run('BEGIN IMMEDIATE')" }, { file: 'lib/repository/stateRepository.js', needle: 'function getTenantWriteQueue' }],
    action: 'Não integrar Jev. Preservar controles de concorrência e contratos monetários; manter qualquer enriquecimento externo antes da transação e revalidar versão, permissão e valores ao persistir.',
    acceptance: 'Testes de concorrência, rollback e valores monetários passam sem rede; nenhum resultado de modelo autoriza override de preço, baixa, aprovação ou consumo de estoque.',
    metrics: 'Conflitos 409, rollback, latência de escrita e violações de invariantes com lib/metrics.js.',
    fallback: 'Conflito → resposta 409 e releitura; falha → rollback. Nunca persistir estado parcialmente validado.',
    tests: ['tests/transaction_isolation.test.cjs', 'tests/lost_update_concurrency.test.cjs', 'tests/monetary_contracts.test.cjs'],
  },
  {
    id: 'chat', number: '09', title: 'Gerar conversa, áudio ou laudo', category: 'Chatbot / geração', status: 'NÃO USAR', stage: 'Modelo inadequado', score: 1, impact: 1, complexity: 5, hours: [24, 48], tokens: 0,
    summary: 'Jev pode escolher um artigo, mas não escrever uma resposta nova nem ouvir o motorista.',
    current: 'Suporte usa textos aprovados; voz utiliza Gemini multimodal e respostas do motor; existem briefing e upload de notas.',
    flow: 'Manter templates e geração/transcrição existentes. Usar Jev somente para os roteamentos separados dos casos 01 e 03.',
    decision: 'NÃO USAR como substituto universal do Gemini, redator do chatbot ou gerador de diagnóstico.',
    benefit: 'Nenhum ganho funcional nessa substituição; perderia modalidades e geração necessárias.',
    pros: ['Escolher resposta pronta é possível e já foi analisado no suporte.'],
    cons: ['Não gera strings livres nem processa áudio/imagem.', 'Encadear escolhas para fabricar texto aumenta complexidade sem vantagem.'],
    risks: 'Piora da experiência e perda de campos livres. Laudo exige validação técnica do responsável.',
    trigger: 'Nenhuma escala justifica usar a versão textual classificadora como transcritor/redator. Reavaliar só com nova capacidade documentada.',
    files: ['services/support/knowledge.js', 'services/voiceActionEngine.js', 'js/voz.js', 'server.js'],
    evidence: [{ file: 'services/voiceActionEngine.js', needle: 'const { text, audioBase64, mimeType }' }, { file: 'server.js', needle: 'async function gerarBriefingExecutivo' }],
    action: 'Não integrar Jev para geração. Documentar separação entre escolher conteúdo aprovado, transcrever, extrair campos e redigir. Preservar os templates e a revisão de laudos; qualquer classificador futuro deve retornar só categorias.',
    acceptance: 'Áudio continua na pipeline multimodal; suporte retorna apenas artigos aprovados; conteúdo não conhecido encaminha a humano. Nenhum laudo novo produzido por escolhas encadeadas.',
    metrics: 'Falha de transcrição, correção de campos, satisfação/encaminhamento e tempo total; sem armazenar áudio em telemetria.',
    fallback: 'Texto digitado, formulário manual, templates e suporte humano.',
    tests: ['tests/voice.test.cjs', 'tests/support_agent.test.cjs', 'tests/assistente_briefing.test.cjs'],
  },
  {
    id: 'moderacao', number: '10', title: 'Moderação e prompt injection', category: 'Moderação', status: 'NÃO USAR', stage: 'Baixo ROI atual', score: 2, impact: 2, complexity: 4, hours: [24, 48], tokens: 0,
    summary: 'Não há feed público; o suporte já restringe saída a artigos e renderiza mensagens como texto.',
    current: 'Suporte autenticado tem quotas e redução de dados; o agente não executa ferramentas nem exibe texto livre do modelo.',
    flow: 'Limites + validação + sanitização + saída restrita. Não inserir Jev como barreira única de segurança ou filtro de todo atendimento.',
    decision: 'NÃO USAR agora para moderar todo texto ou substituir controles contra injeção.',
    benefit: 'Ganho incremental não demonstrado no canal privado atual.',
    pros: ['Classificação de abuso pode ser útil se surgir uma fila real e mensurável.'],
    cons: ['Bloqueio incorreto de pedido legítimo.', 'Modelo também pode ser influenciado por texto adversarial.'],
    risks: 'Censurar relatos de incidente; enviar conteúdo sensível para um segundo fornecedor; confundir filtro com autorização.',
    trigger: 'Reavaliar só se um canal público for efetivamente criado ou houver > 50 abusos/dia revisados por humanos; regras/quotas continuam primeiro.',
    files: ['services/support/router.js', 'services/support/privacy.js', 'services/support/agent.js', 'js/support-widget.js'],
    evidence: [{ file: 'services/support/privacy.js', needle: 'function sanitize' }, { file: 'services/support/agent.js', needle: 'A IA apenas seleciona um conteúdo aprovado' }],
    action: 'Não integrar Jev. Preservar quotas, texto seguro, catálogo fechado e separação de instruções/dados. Verificar casos adversariais no suporte e encaminhamento humano; não bloquear relatos críticos por vocabulário sensível.',
    acceptance: 'HTML e instruções injetadas não executam; pedido de pessoa continua disponível; modelo não ganha ferramentas nem acessa dados de outra oficina.',
    metrics: 'Rejeições por quota, tickets abusivos confirmados, falsos bloqueios e incidentes encaminhados.',
    fallback: 'Encaminhamento humano e limites locais; ausência de classificador não enfraquece autorização.',
    tests: ['tests/support_agent.test.cjs', 'tests/voice_security_negative.test.cjs'],
  },
  {
    id: 'operacao', number: '11', title: 'Alertas, manutenção e pós-venda', category: 'Operação / CRM', status: 'NÃO USAR', stage: 'Regras suficientes', score: 2, impact: 2, complexity: 3, hours: [24, 40], tokens: 0,
    summary: 'Atraso, km, vencimento, fila e cooldown já têm regras explícitas e configuráveis.',
    current: 'Motores de inteligência operacional, manutenção, relacionamento e pós-venda calculam eventos e oportunidades a partir do estado.',
    flow: 'Estado autorizado → limites de horas/km/datas → eventos → política de notificação. Manter cálculos em código.',
    decision: 'NÃO USAR para recalcular urgência baseada em prazo, priorizar mecanicamente boxes ou inventar previsão de churn.',
    benefit: 'Nenhum ganho claro sobre ajustar os limiares existentes com os operadores.',
    pros: ['Uma futura classificação de comentários livres poderia ser separada, se existir demanda.'],
    cons: ['Adiciona rede a cálculos locais.', 'Não há evidência de rótulos para previsão de churn ou falha mecânica.'],
    risks: 'Ocultar alertas críticos, recomendar reparo inadequado ou alterar prioridades sem explicação operacional.',
    trigger: 'Mais volume exige ajuste de limites; só reabrir classificação semântica se houver fila de relatos livres e erros documentados que regras não resolvem.',
    files: ['services/operationalIntelligenceEngine.js', 'services/maintenancePlanService.js', 'services/relationshipService.js', 'services/afterSalesService.js', 'services/operationalNotificationPolicy.js'],
    evidence: [{ file: 'services/operationalIntelligenceEngine.js', needle: 'function avaliarOperacao' }, { file: 'services/maintenancePlanService.js', needle: 'function calcularStatusItem' }],
    action: 'Não integrar Jev. Levantar ruído dos alertas com operadores, ajustar configuração existente e manter regras explícitas de prazo/km/cooldown. Preservar severidades críticas e escopo por tenant.',
    acceptance: 'Mesmo estado e relógio produzem os mesmos eventos; testes de fuso, prazo, km e cooldown permanecem determinísticos. Nenhum alerta crítico depende de provedor externo.',
    metrics: 'Alertas reconhecidos/ignorados, tempo parado, repetição suprimida e taxa de falsos alertas revisada pelo operador.',
    fallback: 'Painel e política local; sem WhatsApp, manter eventos consultáveis no CRM.',
    tests: ['tests/operational_intelligence.test.cjs', 'tests/operational_dashboard.test.cjs', 'tests/crm_fleet_and_maintenance.test.cjs'],
  },
  {
    id: 'fiscal', number: '12', title: 'Fiscal e integração ERP', category: 'ERP / fiscal', status: 'NÃO USAR', stage: 'Contratos exatos', score: 1, impact: 1, complexity: 8, hours: [48, 96], tokens: 0,
    summary: 'Exportação canônica, tributos e sincronização não precisam de classificação probabilística.',
    current: 'ERP usa schemaVersion, cursores e outbox; fiscal tem cálculo decimal e ciclo próprio, com produção bloqueada no escopo documentado.',
    flow: 'Estado → schema canônico → outbox/adapter → confirmação de sincronismo. Cálculo e códigos fiscais validados no fluxo competente.',
    decision: 'NÃO USAR para emitir nota, atribuir alíquota/NCM, calcular imposto ou aceitar sincronização.',
    benefit: 'Nenhuma melhoria clara na correção de contratos de dados.',
    pros: ['Triagem de texto documental é separável e já consta no caso 05.'],
    cons: ['Não substitui parser, schema, cadastro fiscal ou integração real com ERP.', 'Acrescenta risco a dados de efeito financeiro.'],
    risks: 'Classificação fiscal indevida, arredondamento incorreto, sincronismo duplicado e extrapolação do escopo operacional do CRM.',
    trigger: 'Nenhuma escala justifica IA para somas e validade fiscal; só avaliar sugestões de cadastro em outro escopo, com revisão especializada e corpus próprio.',
    files: ['services/erpIntegrationService.js', 'services/fiscal/fiscalCalculationEngine.js', 'services/fiscal/decimal.js', 'services/fiscal/fiscalLifecycleService.js', 'docs/INTEGRACAO_ERP.md'],
    evidence: [{ file: 'services/erpIntegrationService.js', needle: "const SCHEMA_VERSION = '1.0.0'" }, { file: 'services/fiscal/decimal.js', needle: 'BigInt' }],
    action: 'Não integrar Jev. Preservar schemas, cálculo decimal, idempotência e bloqueios de produção. Documentar que sugestão de tipo de documento não determina tributação, emissão ou sincronismo.',
    acceptance: 'Contratos ERP e testes de ciclo fiscal passam sem rede/modelo; emitir continua sujeito aos bloqueios e configurações atuais.',
    metrics: 'Falhas de schema, fila/retries ERP, rejeições fiscais e divergências conciliadas.',
    fallback: 'Reter pendência para revisão e retry idempotente; manter emissão real no ERP homologado conforme escopo.',
    tests: ['tests/erp_integration.test.cjs', 'tests/fiscal_calculation.test.cjs', 'tests/fiscal_hardening.test.cjs'],
  },
  {
    id: 'automacoes', number: '13', title: 'Automações e continuidade', category: 'Automação / infraestrutura', status: 'NÃO USAR', stage: 'Confiabilidade primeiro', score: 1, impact: 1, complexity: 6, hours: [24, 48], tokens: 0,
    summary: 'Agendar, deduplicar, supervisionar e restaurar são problemas de engenharia determinística.',
    current: 'Scheduler outbox, políticas de envio, supervisor Windows e scripts de backup/restore já existem. Documentação do piloto registra pendências de backup independente.',
    flow: 'Agenda/regras → outbox → envio e registro; backup → verificação → ensaio de restauração. Nenhuma decisão Jev no caminho.',
    decision: 'NÃO USAR para escolher se um backup é íntegro, quando executar um job obrigatório ou se deve restaurar.',
    benefit: 'O ROI está na confiabilidade operacional e no fechamento das pendências documentadas, não em um classificador adicional.',
    pros: ['Não há vantagem demonstrada do modelo nas rotinas existentes.'],
    cons: ['Dependência de internet num piloto local.', 'IA não torna fila, armazenamento ou serviço Windows mais duráveis.'],
    risks: 'Silenciar falha de backup, repetir envio ou deixar job obrigatório sem execução.',
    trigger: 'Múltiplas instâncias justificam coordenação durável; falha de restore exige correção operacional. Nenhum desses eventos justifica Jev.',
    files: ['lib/outbox/scheduler.js', 'services/backupService.js', 'services/operationalNotificationPolicy.js', 'scripts/supervise_patio.cjs', 'scripts/executar_backup_operacional.cjs'],
    evidence: [{ file: 'lib/outbox/scheduler.js', needle: 'async function processarProximoJob' }, { file: 'docs/INSTALADOR_TRES_EMPRESAS_2026-09-23.md', needle: 'Backup independente' }],
    action: 'Não integrar Jev. Confirmar o estado atual das pendências documentadas e priorizar ensaio isolado de restore, observabilidade de falhas e contratos de claim/retry da fila se a topologia mudar. Não executar restore sobre banco real.',
    acceptance: 'Backup íntegro validado por ferramentas determinísticas, restauração em destino isolado e jobs com comportamento definido para crash/retry. Relatar limites da instância única.',
    metrics: 'Idade do último backup válido, resultado do restore, fila pendente, tentativas, falhas finais e reinícios.',
    fallback: 'Alerta operacional e procedimento humano documentado; nunca aceitar integridade por score de IA.',
    tests: ['tests/wal_backup_and_recovery.test.cjs', 'tests/operational_backup_external.test.cjs', 'tests/supervisor_isolated.test.cjs'],
  },
];

function implementationPrompt(c) {
  const classification = c.status !== 'NÃO USAR';
  return `Trabalhe no repositório Pátio CRM (Node.js CommonJS/Express, frontend JS modular, SQLite WAL).
Caso ${c.number}: ${c.title}. Recomendação: ${c.status} — ${c.stage}.
${classification ? 'Implemente um experimento opcional e reversível; não habilite em produção automaticamente.' : 'Este caso foi rejeitado para Jev. Implemente/verifique a alternativa determinística abaixo; não instale nem chame Jev.'}

CONTEXTO VERIFICADO
${c.current}
Fluxo alvo: ${c.flow}
Arquivos existentes: ${c.files.join(', ')}.
Confira o conteúdo atual e as instruções do repositório; os nomes de arquivos são referências, não autorização para refatorar módulos sem necessidade. Preserve mudanças do usuário.

ESCOPO
${c.action}
Gatilho de negócio: ${c.trigger}
${classification ? `Contrato: conferir https://docs.typesafe.ai/api e /models antes de codificar; usar POST https://api.typesafe.ai/v1/systemone com state minimizado, model fixado (jev-1.13.0 era o documentado em 28/09/2026) e questions. Choice: criteria com opções existentes e desconhecido; resposta answers[id].choice/probabilities/confidence. Noul: answers[id].noul, sem confidence independente. Nunca confundir confiança com acurácia medida. IDs/classes devem ser allowlisted e números finitos validados mesmo com saída tipada.
Criar adapter server-side injetável em services/ai/jevClassifier.js, com flag por caso desativada, chave TYPESAFE_API_KEY apenas no ambiente, limite de payload/orçamento e timeout inicial configurável de 1.500 ms. Evitar retry síncrono em cascata; tratar 429/5xx com fallback e circuito por processo, documentando limite de instância única. Não usar alias móvel sem reavaliação. Não colocar chave no frontend. Não transmitir state completo, código, histórico amplo, senhas ou tokens. Confirmar consentimento para TypeSafe e política de dados antes de qualquer tráfego real; testes usam mocks e corpus sintético/revisado. Não abrir transação SQLite durante espera externa. Não adicionar outra base, fila ou microserviço sem necessidade.` : 'Custo recomendado de integração Jev: zero. Faça primeiro uma revisão delimitada; só altere código se houver falha ou melhoria concreta demonstrada.'}

CRITÉRIOS DE ACEITE
${c.acceptance}
Preservar isolamento por tenant, RBAC, confirmação humana/token, versionamento e idempotência. Nenhum score altera estas garantias. Escrever testes dirigidos de falha e fronteira, não testes que apenas reproduzem a implementação.
Testes existentes relevantes: ${c.tests.join(', ')}. Usar scripts/test-preload.cjs quando exigido pela suíte, bancos temporários e integrações desativadas; não importar banco real em ensaios. Só afirmar testes efetivamente executados.

OBSERVABILIDADE
${c.metrics}
${classification ? 'Separar previsão, abstenção e resultado revisado; registrar versão de regras/modelo e request ID, nunca conteúdo bruto. Exportar comparação de baseline e candidato, incluindo falhas, revisão humana e custo total. Limiares calibrados em desenvolvimento e verificados em holdout PT-BR; não escolher limiar arbitrário como garantia.' : 'Reutilizar métricas existentes; sem coletar dados adicionais desnecessários.'}

FALLBACK E REVERSÃO
${c.fallback}
${classification ? 'Provar flag off, timeout, indisponibilidade, resposta inválida e reinício em testes. Sem credencial/acesso, entregar adapter mockado, corpus e relatório pendente; não simular ganhos medidos. Produção só após resultado econômico e validação pelo responsável.' : 'Manter o comportamento determinístico e documentar riscos residuais.'}

ENTREGA
Diff pequeno, instruções de execução, evidências dos testes e relatório do que foi medido versus estimado. Não alterar .env, banco operacional, deploy-piloto, credenciais ou liberar integrações bloqueadas. Não publicar nem enviar mensagens externas como parte deste trabalho.`;
}

module.exports = {
  date: '28/09/2026', pricePerMillionUSD: 0.042,
  headline: 'Um bom encaixe. Nenhuma razão para espalhar IA pelo CRM.',
  verdict: 'Avaliar o roteamento de suporte agora; manter as regras críticas em código. Nenhuma integração Jev está aprovada para produção com as evidências disponíveis.',
  methodology: 'Scores são julgamento técnico de utilidade incremental, não acurácia, probabilidade nem ROI medido. 0 = sem encaixe; 1–3 = regras superiores ou pouco ganho; 4–6 = ganho condicionado; 7–8 = encaixe forte e limitado; 9–10 exigiriam evidência operacional, ausente aqui. Impacto e complexidade vão de 0 a 10. Esforços são estimativas para integração + avaliação de um desenvolvedor familiarizado; nos casos rejeitados mostram o custo evitável de tentar Jev. Custos usam R$ 100/h apenas como hipótese editável. Gatilhos de escala e critérios numéricos são propostas para decisão, não métricas observadas.',
  scope: 'Inventário de arquivos, rotas e testes; leitura dirigida dos pontos de decisão e seus chamadores em frontend, API, autenticação, suporte, voz, triagem, documentos/WhatsApp, cobrança, persistência, fiscal/ERP, operação, automações e implantação. Não é auditoria linha a linha nem certificação de segurança. Não foram lidos .env, banco, uploads, sessões ou dados de clientes. Sem chamada real à TypeSafe ou benchmark do Jev. Testes históricos nos documentos não foram tratados como testes executados nesta análise.',
  pilot: 'O documento de distribuição de 23/09/2026 descreve três instalações independentes para testes fictícios, integrações desativadas e backup independente/restore pendentes. É evidência documental, não consulta ao estado atual das instalações.',
  next: [
    { title: 'Medir antes de integrar', text: 'Instrumentar o suporte atual e montar corpus PT-BR. Contar somente dúvidas não resolvidas localmente; separar correção de artigo, latência e tempo humano. Não há volume real medido nesta análise.' },
    { title: 'Comparar três alternativas', text: 'Busca local com sinônimos, classificação Gemini atual e Jev. Testar em ambiente isolado. O gasto de tokens sozinho não paga a engenharia; usar custo total e custo dos erros.' },
    { title: 'Fechar prioridades do piloto', text: 'Verificar pendências de backup independente e restauração. O menu WhatsApp ainda descreve baixas e compras automáticas que o handler bloqueia: alinhar esse texto evita expectativas erradas sem Jev.' },
  ],
  sources, cases: cases.map(c => ({ ...c, prompt: implementationPrompt(c) })),
};
