'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'patio-db-safety-'));process.env.DB_PATH=path.join(dir,'test.db');
const db=require('../db');
test('Migração concorrente, falha de disco e carga transacional limitada', {timeout:60000},async t=>{
 t.after(async()=>{await db.closeDB();fs.rmSync(dir,{recursive:true,force:true});});
 await t.test('inicializações concorrentes não duplicam colunas',async()=>{await Promise.all([db.initDB(),db.initDB(),db.initDB()]);const fields=await db.all('PRAGMA table_info(fiscal_documents)');assert.equal(fields.filter(f=>f.name==='config_snapshot_json').length,1);});
 await db.run('CREATE TABLE safety(id TEXT PRIMARY KEY, value BLOB)');
 await t.test('run comum externo não participa do rollback de outra operação',async()=>{let entered,release;const ready=new Promise(r=>entered=r),hold=new Promise(r=>release=r);const a=db.transaction(async()=>{await db.run('INSERT INTO safety VALUES (?,?)',['a','uncommitted']);entered();await hold;throw Error('rollback');});const result=a.catch(e=>e);await ready;assert.equal(await db.get('SELECT * FROM safety WHERE id=?',['a']),undefined);const b=db.run('INSERT INTO safety VALUES (?,?)',['b','durable']);release();assert.match((await result).message,/rollback/);await b;await db.closeDB();await db.openDB();assert.equal((await db.get('SELECT value FROM safety WHERE id=?',['b'])).value,'durable');});
 await t.test('SQLITE_FULL reverte só a transação correspondente',async()=>{await assert.rejects(db.transaction(async tx=>{const pages=await tx.get('PRAGMA page_count');await tx.run('PRAGMA max_page_count='+pages.page_count);await tx.run("INSERT INTO safety VALUES ('full',zeroblob(2000000))");}),/SQLITE_FULL/);assert.equal(await db.get("SELECT * FROM safety WHERE id='full'"),undefined);assert.equal((await db.get("SELECT value FROM safety WHERE id='b'")).value,'durable');});
 await t.test('100 operações em ondas 1, 4 e 10 sem perda e abaixo de 30s por onda',async()=>{const results=[];for(const concurrency of [1,4,10]){const start=performance.now(),times=[];let next=0;await Promise.all(Array.from({length:concurrency},async()=>{while(next<100){const id=next++,begin=performance.now();await db.transaction(()=>db.run('INSERT INTO safety VALUES (?,?)',[concurrency+'-'+id,'committed']));times.push(performance.now()-begin);}}));times.sort((a,b)=>a-b);const durationMs=Math.round(performance.now()-start);assert.ok(durationMs<30000);results.push({operations:100,concurrency,durationMs,p95Ms:Math.round(times[94])});}assert.equal((await db.get('SELECT COUNT(*) AS n FROM safety')).n,301);console.log('MEASUREMENT_LOCAL_SQLITE '+JSON.stringify(results));});
 await t.test('DB_PATH real explícito e caminho equivalente são recusados antes de abrir',async()=>{await assert.rejects(db.openDB(path.join(__dirname,'..','patio.db')),/DB_GUARD/);await assert.rejects(db.openDB(path.join(__dirname,'..','scratch','..','patio.db')),/DB_GUARD/);});
});
