'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'patio-fiscal-hardening-'));
process.env.DB_PATH=path.join(root,'db.sqlite');process.env.BACKUP_DIR=path.join(root,'backups');process.env.UPLOAD_DIR=path.join(root,'uploads');
process.env.FISCAL_ENCRYPTION_KEY=crypto.randomBytes(32).toString('hex');delete process.env.FISCAL_TEST_ADAPTER;
const db=require('../db'),config=require('../services/fiscal/fiscalConfigService'),life=require('../services/fiscal/fiscalLifecycleService'),review=require('../services/fiscal/review'),events=require('../services/fiscal/fiscalEventService');
const {FocusNFeAdapter,getFiscalProviderAdapter}=require('../services/fiscal/fiscalProviderAdapter');
const decimal=require('../services/fiscal/decimal');
const response=data=>({ok:true,status:200,text:async()=>typeof data==='string'?data:JSON.stringify(data)});
const key='35260911222333000181550010000000011000000010',protocol='9'.repeat(15);
const xml=`<nfeProc><NFe><infNFe Id="NFe${key}"></infNFe></NFe><protNFe><infProt><tpAmb>2</tpAmb><cStat>100</cStat><nProt>${protocol}</nProt></infProt></protNFe></nfeProc>`;
const item={codigoInterno:'TESTE',descricao:'ITEM SINTÉTICO SEM VALIDADE FISCAL',quantidade:'1',valorUnitario:'100',unidade:'UN',ncm:'00000000',cfop:'5102',origem:'0',csosn:'102',cstPIS:'07',cstCOFINS:'07',aliquotaICMS:0,aliquotaPIS:0,aliquotaCOFINS:0,aliquotaCBS:0,aliquotaIBS:0};
const dest={documento:'11122233344',nome:'DESTINATÁRIO SINTÉTICO',logradouro:'Rua de teste',numero:'1',bairro:'Teste',municipio:'Teste',codigoMunicipio:'3509502',uf:'SP',cep:'00000000',indicadorIE:'9'};
const profile={tipo:'documento',modelo:'55',versao:'fixture-local-1',validadoPor:'test-only',vigenteDesde:'2020-01-01',vigenteAte:'2099-01-01',reformaValidada:true,numeracaoValidada:true,cnpj:'11222333000181',uf:'SP',municipio:'3509502',regime:'simples_nacional',campos:{natureza_operacao:'Teste local',tipo_documento:1,finalidade_emissao:1,local_destino:1,consumidor_final:1,presenca_comprador:1,modalidade_frete:9}};

test('Controles fiscais, transporte real com respostas sintéticas e isolamento', {timeout:30000}, async t=>{
 await db.initDB();const originalFetch=global.fetch;t.after(async()=>{global.fetch=originalFetch;await db.closeDB();fs.rmSync(root,{recursive:true,force:true});});
 await config.saveFiscalConfig('tenant_a',{provider:'focus_nfe',providerToken:'synthetic-token-not-a-credential',cnpj:profile.cnpj,razaoSocial:'Emitente sintético',uf:'SP',codigoMunicipioIbge:'3509502',regimeTributario:'simples_nacional',inscricaoEstadual:'ISENTO',regrasTributarias:[profile]});
 await t.test('não há fallback simulado, produção ou segredo fixo',async()=>{assert.throws(()=>getFiscalProviderAdapter('mock_homologacao',null,'homologacao'),/Simulação/);assert.throws(()=>new FocusNFeAdapter('x','producao'),/bloqueada/);await assert.rejects(config.saveFiscalConfig('tenant_a',{ambiente:'producao'}),/bloqueada/);const pub=await config.getPublicFiscalConfig('tenant_a');assert.equal(pub.providerToken,undefined);assert.equal(pub.isProductionReady,false);});
 await t.test('rateio conserva centavos em 2000 combinações determinísticas',()=>{for(let n=1;n<=2000;n++){const total=(n%997)/100,values=decimal.allocate(total,[n%11,n%17,n%3]);assert.equal(values.reduce((a,v)=>a+Math.round(v*100),0),Math.round(total*100));assert.ok(values.every(v=>v>=0));}assert.equal(decimal.product('3','0.3333'),1);assert.equal(decimal.round(0.1+0.2),.3);assert.throws(()=>decimal.scaled('-1'));});
 let draft;
 await t.test('idempotência concorrente isolada por oficina, colisão de conteúdo recusada',async()=>{const args={tenantId:'tenant_a',modelo:'55',destinatario:dest,itens:[item],idempotencyKey:'same_operation_key'};const [a,b]=await Promise.all([life.criarRascunhoDocumentoFiscal(args),life.criarRascunhoDocumentoFiscal(args)]);assert.equal(a.id,b.id);draft=a;await assert.rejects(life.criarRascunhoDocumentoFiscal({...args,itens:[{...item,valorUnitario:200}]}),/outro conteúdo/);const other=await life.criarRascunhoDocumentoFiscal({...args,tenantId:'tenant_b'});assert.notEqual(other.id,a.id);assert.equal(await life.obterDocumentoFiscalPorId(a.id,'tenant_b'),null);});
 await t.test('classificação e alíquotas ausentes impedem revisão',async()=>{const bad=await life.criarRascunhoDocumentoFiscal({tenantId:'tenant_a',itens:[{descricao:'Incompleto',quantidade:1,valorUnitario:10}],destinatario:dest});await assert.rejects(review.reviewDocument({documentId:bad.id,tenantId:'tenant_a',actorId:'reviewer'}),/informe/);});
 let posts=0;
 await t.test('intenção precede rede, timeout fica incerto e repetição não envia',async()=>{await review.reviewDocument({documentId:draft.id,tenantId:'tenant_a',actorId:'reviewer'});global.fetch=async(url,options)=>{assert.equal(new URL(url).origin,'https://homologacao.focusnfe.com.br');assert.equal(options.redirect,'error');posts++;const row=await db.get('SELECT status,numero FROM fiscal_documents WHERE id=?',[draft.id]);assert.equal(row.status,'transmitindo');assert.ok(row.numero>0);throw Error('Timeout sintético após envio');};await assert.rejects(life.transmitirDocumentoFiscal({documentId:draft.id,tenantId:'tenant_a'}),/Timeout/);assert.equal((await life.obterDocumentoFiscalPorId(draft.id,'tenant_a')).status,'processando');await assert.rejects(life.transmitirDocumentoFiscal({documentId:draft.id,tenantId:'tenant_a'}),/incerto/);assert.equal(posts,1);});
 await t.test('consulta reconcilia protocolo e XML sem reenviar, snapshot permanece',async()=>{global.fetch=async(url,options)=>{assert.ok(!options?.method||options.method==='GET');return response(url.endsWith('.xml')?xml:{status:'autorizado',chave_nfe:key,caminho_xml_nota_fiscal:'/files/note.xml',status_sefaz:'100'});};const result=await life.consultarSituacaoDocumentoFiscal({documentId:draft.id,tenantId:'tenant_a'});assert.equal(result.status,'autorizado');assert.equal(result.documento.protocoloAutorizacao,protocol);assert.equal(result.documento.xmlSha256,crypto.createHash('sha256').update(xml).digest('hex'));await config.saveFiscalConfig('tenant_a',{regrasTributarias:[]});const frozen=await db.get('SELECT config_snapshot_json FROM fiscal_documents WHERE id=?',[draft.id]);assert.equal(JSON.parse(frozen.config_snapshot_json).regrasTributarias[0].versao,profile.versao);assert.ok(!frozen.config_snapshot_json.includes('synthetic-token'));});
 await t.test('evento incerto permanece e impede repetição concorrente',async()=>{global.fetch=async()=>{throw Error('Rede interrompida');};await assert.rejects(events.emitirCartaCorrecao({documentId:draft.id,tenantId:'tenant_a',correcao:'Correção sintética com tamanho permitido'}),/interrompida/);await assert.rejects(events.emitirCartaCorrecao({documentId:draft.id,tenantId:'tenant_a',correcao:'Outra correção não deve ser enviada'}),/incerto/);assert.equal((await events.listarEventosDocumento(draft.id,'tenant_a'))[0].status,'processando');});
 await t.test('XML externo, XXE, resposta vazia e HTTP 200 sem autorização não liberam',async()=>{const adapter=new FocusNFeAdapter('test','homologacao',{transport:async()=>response('<!DOCTYPE x [<!ENTITY e SYSTEM "file:///x">]><nfeProc/>')});await assert.rejects(adapter.downloadXml('https://evil.invalid/file.xml'),/Origem/);await assert.rejects(adapter.downloadXml('/safe.xml'),/segurança/);assert.equal(adapter.normalize({status:'autorizado'}, {modelo:'55'}).status,'processando');assert.equal(adapter.normalize({ok:true}, {modelo:'55'}).status,'processando');});
 await t.test('contrato de CC-e recupera protocolo do XML e aceita chave prefixada documentada',async()=>{
   const eventXml='<procEventoNFe><evento><chNFe>'+key+'</chNFe><tpEvento>110110</tpEvento></evento><retEvento><nProt>'+protocol+'</nProt></retEvento></procEventoNFe>';
   const adapter=new FocusNFeAdapter('test','homologacao',{transport:async(url,options)=>response(options?.method==='POST'?{status:'autorizado',status_sefaz:'135',caminho_xml_carta_correcao:'/event.xml',numero_carta_correcao:1}:eventXml)});
   assert.equal(adapter.normalize({status:'autorizado',chave_nfe:'NFe'+key},{modelo:'55'}).chaveAcesso,key);
   const result=await adapter.enviarCCE({doc:{id:'local',modelo:'55',chaveAcesso:key},correcao:'Correção sintética de endereço'});
   assert.equal(result.ok,true);assert.equal(result.protocoloCCE,protocol);assert.equal(result.xml,eventXml);
   assert.equal(result.xmlSha256,crypto.createHash('sha256').update(eventXml).digest('hex'));
 });
 await t.test('falha de certificado/provedor nunca é convertida em autorização',async()=>{
   const adapter=new FocusNFeAdapter('test','homologacao',{transport:async()=>({ok:false,status:422,text:async()=>JSON.stringify({error:'certificado vencido',token:'never-expose-this'})})});
   await assert.rejects(adapter.consultarSituacao({doc:{id:'local',modelo:'55'}}),error=>/HTTP 422/.test(error.message)&&!error.message.includes('never-expose'));
 });
 await t.test('calibração nunca recua e recuperação bloqueia novas transmissões',async()=>{const numbering=require('../services/fiscal/fiscalNumberingService');await numbering.calibrarUltimoNumero({tenantId:'tenant_a',ultimoNumero:100});const result=await numbering.calibrarUltimoNumero({tenantId:'tenant_a',ultimoNumero:1});assert.equal(result.ultimoNumero,100);fs.writeFileSync(process.env.DB_PATH+'.fiscal-recovery-required','pending');await assert.rejects(life.transmitirDocumentoFiscal({documentId:draft.id,tenantId:'tenant_a'}),/restaurado/);fs.unlinkSync(process.env.DB_PATH+'.fiscal-recovery-required');});
 await t.test('API nega suporte, outra oficina e alteração de segredos',async()=>{const express=require('express'),app=express();app.use(express.json());app.use((req,res,next)=>{req.securityContext={actorType:'user',actorId:'test',role:req.headers['x-role']||'admin',tenantId:req.headers['x-tenant']||'tenant_a',permissions:[]};next();});app.use('/api/fiscal',require('../services/fiscal/router').createFiscalRouter());const server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s));});try{global.fetch=originalFetch;const base='http://127.0.0.1:'+server.address().port+'/api/fiscal';assert.equal((await fetch(base+'/config',{headers:{'x-role':'platform_support'}})).status,403);assert.equal((await fetch(base+'/documentos/'+draft.id,{headers:{'x-tenant':'tenant_b'}})).status,404);assert.equal((await fetch(base+'/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({providerToken:'must-not-persist'})})).status,400);assert.equal((await fetch(base+'/documentos/'+draft.id+'/xml')).status,200);}finally{await new Promise(r=>server.close(r));}});
});
